<template>
  <header class="h-[100px] flex justify-evenly items-center slide-in-left ">
    
    <router-link
      class="uppercase no-underline hover:border-b-2 border-solid border-primary"
      to="/matches"
      >{{$t("Matches")}}</router-link
    >
    <router-link
      class="uppercase no-underline hover:border-b-2 border-solid border-primary"
      to="/myBets"
      >{{$t("MyBets")}}</router-link
    >
    <select aria-label="LanguageSelect" v-model="language" @change="setLanguage">
      <option value="hu">HU</option>
      <option value="en">EN</option>
     </select>
     
  </header>
</template>

<script>
 export default {
  data() {
    return{
language: 'hu'
    }
  },
  methods: {
    setLanguage(){
      this.$i18n.locale=this.language
    }
  }
  
 }
 </script>
 <style scoped>
.slide-in-left {
	-webkit-animation: slide-in-left 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	animation: slide-in-left 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2025-3-3 11:19:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
 </style>